version: '3.4'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: manuscript2022
      MYSQL_DATABASE: ManuscriptInfo
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
