version: '3.4'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: manuscript2022
      MYSQL_DATABASE: ManuscriptInfo
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ADMIN
    restart: always
    ports:
      - "27017:27017"
